name: Build, Test, and Generate Allure Report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run integration tests with Gradle
        run: ./gradlew test
  Allure_report:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Generate Allure report
        run: |
          ./gradlew allureReport
          echo "Allure report live here - https://${{ github.repository }}/-/jobs/${{ github.job_id }}/artifacts/build/reports/allure-report/allureReport/index.html"
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: build/reports/allure-report/allureReport/
  artifacts:
    when: always
    paths:
      - build/reports/allure-report/allureReport/
