# Образ для сборки
image: gradle:alpine
on: [push]

# Определение этапов
stages:
  - test
  - report

# Определение работы для запуска тестов и генерации отчета в Allure
test:
  # Задание этапа
  stage: test
  # Определение скриптов для выполнения работы
  script:
    - ./gradlew clean test
    - ./gradlew allureReport
  # Определение артефактов для сохранения
  artifacts:
    when: always
    paths:
      - build/reports/allure-report
      - build/test-results

# Определение работы для загрузки отчета в Allure
report:
  # Задание этапа
  stage: report
  # Определение скриптов для выполнения работы
  script:
    - ./gradlew allureServe
  # Определение правил загрузки отчета в Allure Serve
  env:
    # Указание URL для доступа к отчету в Allure Serve
    ALLURE_SERVER_URL: https://example.com/allure
  # Определение секретов для загрузки отчета в Allure Serve
  secrets:
    # Токен доступа к Allure Serve
    ALLURE_SERVER_TOKEN: ${{ secrets.ALLURE_SERVER_TOKEN }}
