name: Build and Test with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run integration tests with Gradle
        run: ./gradlew integrationTest
      - name: Generate Allure report
        run: ./gradlew allureReport

    allure-report:
      needs: integration-test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Generate Allure report
          uses: allure-framework/allure-github-action@v2
          with:
            allure-version: '2.14.0'
            results-directory: build/allure-results
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}