name: Integration tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Установка java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Разрешение на чтение, выполнение
        run: chmod +x gradlew

      - name: запуск тестов
        run: ./gradlew clean test

      - name: Генерация отчета
        uses: allure-framework/allure-github-action@v2
        with:
          version: '2.16.0'
          include: '**/allure-results'
